version: '3.5'

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal

  uwsgi:
    restart: always
    # image: vanessa/sregistry
    build:
      context: ./sregistry
    volumes:
      - ./sregistry:/code
      - www_static:/var/www/static
      - singularity_images:/var/www/images
      # uncomment for PAM auth
      #- /etc/passwd:/etc/passwd
      #- /etc/shadow:/etc/shadow
    links:
      - redis
      - db
    networks:
      - internal

  nginx:
    restart: always
    # image: vanessa/sregistry_nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
      - .:/code
      - www_static:/var/www/static
      - singularity_images:/var/www/images
    links:
      - uwsgi
      - db
    networks:
      - internal
      - external

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - internal


  worker:
    #image: vanessa/sregistry
    build:
      context: ./sregistry
    command: celery worker -A shub.celery -Q default -n default@%h -B
    volumes:
      - .:/code
      - www_static:/var/www/static
      - singularity_images:/var/www/images
    networks:
      - internal
#    links:
#      - redis
#      - db

volumes:
  pg_data:
  www_static:
  singularity_images:

networks:
  internal:
  external: