version: '3'

services:
  db:
    image: postgres
    env_file: env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal

  uwsgi:
    restart: always
    build:
      context: ./sregistry
    env_file: env
    volumes:
      - ./sregistry:/code
      - www_static:/var/www/static
      - singularity_images:/var/www/images
    depends_on:
      - redis
      - db
    networks:
      - internal

  nginx:
    restart: always
    build:
      context: ./nginx
    env_file: env
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./sregistry/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
      - www_static:/var/www/static
      - singularity_images:/var/www/images
    depends_on:
      - uwsgi
    networks:
      - internal
      - external

  redis:
    restart: always
    image: redis:latest
    env_file: env
    ports:
      - "6379:6379"
    networks:
      - internal

  worker:
    build:
      context: ./sregistry
    env_file: env
    command: celery worker -A shub.celery -Q default -n default@%h -B
    volumes:
      - www_static:/var/www/static
      - singularity_images:/var/www/images
    networks:
      - internal
    depends_on:
      - redis
      - db

volumes:
  pg_data:
    external: true
  www_static:
  singularity_images:
    external: true

networks:
  internal:
  external: