version: '3'

services:
  jenkins:
    build: 
      context: ./jenkins
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - internal

  nginx:
    volumes:
      - ./jenkins.conf:/etc/nginx/conf.d/jenkins.conf
    depends_on:
      - jenkins

volumes:
  jenkins-log:
    external: true

  jenkins-data:
    external: true
